#!/bin/sh
b=$(basename $1 .c)
echo  $b":"
fcc -m68hc11 -X -c tests/$b.c
ldhc11 -b -C32768 testcrt0_68hc11.o tests/$b.o -o tests/$b /opt/fcc/lib/hc11/libhc11.a
./emu6800 -d 6811 tests/$b tests/$b.map 2> $b.log

