#!/bin/sh
b=$(basename $1 .c)
echo  $b":"
fcc -m6800 -O -X -c tests/$b.c
ld6800 -b -Z0 -C256 testcrt0_6800.o tests/$b.o -o tests/$b /opt/fcc/lib/6800/lib6800.a
./emu6800 -d 6800 tests/$b tests/$b.map 2> $b.log
