#!/bin/sh
b=$(basename $1 .c)
echo  $b":"
fcc -O -X -msm83 -c tests/$b.c
ldsm83 -b -C0 testcrt0_sm83.o tests/$b.o -o tests/$b /opt/fcc/lib/sm83/libsm83.a -m tests/$b.map
./emusm83 -d tests/$b tests/$b.map 2> $b.log
