#!/bin/sh
if [ "$#" -lt 2 ]
then echo "Usage: $0 c_file cpu {opt}"; exit 1
fi

FILE=$1
shift
. ./cpuparam.sh

# Make cprintf.o
fcc -m$CPU $OPT -c cprintf.c

b=$(basename $FILE .c)
echo "$FILE:"
fcc -m$CPU $OPT -c $b.c

$LINK -b $LINKOPT -o $b \
	../testcrt0_$CPU.o cprintf.o $b.o \
	/opt/fcc/lib/$LIB/lib$LIB.a -m $b.map
../$EMU -d $b $b.map 2> $b.log
#rm -f $b.o $b $b.map 
fcc -m$CPU $OPT -S $b.c
fcc -m$CPU $OPT -S cprintf.c
