#!/bin/sh
# Run each test and compare
# against known good output
OPT=""

case "x"$1 in
	x6303)
		CPU=6803
		LINK=ld6800
		LINKOPT="-C256 -Z0"
		EMU="emu6800 6303"
		break
		;;
	x6502)
		CPU=6502
		LINK=ld6502
		LINKOPT="-C512 -Z0"
		EMU=emu6502
		break
		;;
	x6800)
		CPU=6800
		LINK=ld6800
		LINKOPT="-C256 -Z0"
		EMU="emu6800 6800"
		break
		;;
	x6803)
		CPU=6803
		LINK=ld6800
		LINKOPT="-C256 -Z0"
		EMU="emu6800 6803"
		break
		;;
	x6809)
		CPU=6809
		LINK=ld6809
		LINKOPT=-C256
		EMU=emu6809
		break
		;;
	x8070)
		CPU=8070
		LINK=ld8070
		LINKOPT="-C1 -Z0xFF00"
		EMU=emu807x
		break
		;;
	x8080)
		CPU=8080
		LINK=ld8080
		LINKOPT="-C256"
		EMU=emu85
		break
		;;
	x8085)
		CPU=8085
		LINK=ld8080
		LINKOPT="-C256"
		EMU=emu85
		break
		;;
	xtms7000)
		CPU=tms7000
		LINK=ld7000
		LINKOPT="-C0x200"
		EMU=emu7k
		break
		;;
	xz80)
		CPU=z80
		LINK=ldz80
		LINKOPT="-C0"
		EMU=emuz80
		break
		;;
	*)
		echo "Unknown processor"
		exit 1
		;;
esac

if [ x"$2" != x ]; then
	OPT=$2
fi

# Make cprintf.o
fcc -m$CPU $OPT -c cprintf.c

# Try to use each input source file
for i in input*c
# We can't do anything if there's no file to test against
do if [ ! -f "out.$i" -a ! -f "err.$i" ]
   then echo "Can't run test on $i, no output file!"

   # Output file: compile the source, run it and
   # capture the output, and compare it against
   # the known-good output
   else if [ -f "out.$i" ]
        then
	  # Print the test name, compile it
	  # with our compiler
	  b=$(basename $i .c)
          echo -n $i
	  fcc -m$CPU $OPT -c $b.c

	  # Link the output, run it
	  # and get the output in trial.$i
	  $LINK -b $LINKOPT -m $b.map \
		../testcrt0_$CPU.o cprintf.o \
		$b.o -o $b \
		/opt/fcc/lib/$CPU/lib$CPU.a
          ../$EMU $b $b.map > trial.$i
	  rm -f $b.o $b $b.map

  	  # Compare this agains the correct output
          cmp -s "out.$i" "trial.$i"

	  # If different, announce failure
          # and print out the difference
          if [ "$?" -eq "1" ]
          then echo ": failed"
            diff -c "out.$i" "trial.$i"
            echo

	  # No failure, so announce success
          else echo ": OK"
          fi

   # Error file: compile the source and
   # capture the error messages. Compare
   # against the known-bad output. Same
   # mechanism as before.
   #
   # NOTE: Warren took out all these tests
   # as the fcc error messages are different
   # to the acwj error messages.
   #
   else if [ -f "err.$i" ]
        then
          echo -n $i
          ../comp1 $i 2> "trial.$i"
          cmp -s "err.$i" "trial.$i"
          if [ "$?" -eq "1" ]
          then echo ": failed"
            diff -c "err.$i" "trial.$i"
            echo
          else echo ": OK"
          fi
        fi
     fi
   fi
   rm -f out out.s "trial.$i"
done
