#!/usr/bin/env python3
"""BLIP opcode-map generator + validator.

Single source of truth: isa/opcodes.toml. Every other opcode artifact derives
from it (R-BUILD-3 discipline, toolchain.md P1): the isa.md §8.2 inventory table,
the future assembler mnemonic table (as6-blip), and the D-40 opcode→start-address
LUT. Do not hand-edit those; edit isa/opcodes.toml and regenerate.

Subcommands:
  check      validate bytes (unique / dense / in-range / length budget); exit 1 on error
  emit-md    print the §8.2 page sections (markdown) to stdout
  write-md   splice emit-md into docs/isa.md between the inventory markers
  emit-json  print a JSON opcode list for the assembler

The byte assignment is mechanical and sequential per page; 0x80 is reserved as the
page-1 prefix and so is skipped on page 0 (isa.md §5.1, §8.1; D-41, D-48).
"""
import argparse, json, sys, tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOML = ROOT / "isa" / "opcodes.toml"
ISA_MD = ROOT / "docs" / "isa.md"
BEGIN = "<!-- BEGIN opcode-inventory (generated from isa/opcodes.toml by tools/isa/gen_opcodes.py — do not edit by hand) -->"
END = "<!-- END opcode-inventory -->"
PAGE_TITLE = {0: "hot (no prefix)", 1: "cold (`0x80` prefix)"}


def load():
    return tomllib.loads(TOML.read_text())["op"]


def by_page(ops):
    return {p: [o for o in ops if o["page"] == p] for p in (0, 1)}


def expected_bytes(n, page):
    out, b = [], 0
    for _ in range(n):
        if page == 0 and b == 0x80:
            b += 1
        out.append(b)
        b += 1
    return out


def check(ops):
    errs = []
    pages = by_page(ops)
    for page, pl in pages.items():
        maxlen = 3 if page == 0 else 4
        bs = [o["byte"] for o in pl]
        for o in pl:
            if not 0 <= o["byte"] <= 0xFF:
                errs.append(f"page{page} {o['mnem']!r}: byte 0x{o['byte']:X} out of range")
            if page == 0 and o["byte"] == 0x80:
                errs.append(f"page0 {o['mnem']!r}: uses 0x80 (reserved page-1 prefix)")
            if o["length"] > maxlen:
                errs.append(f"page{page} {o['mnem']!r}: length {o['length']} > {maxlen}")
        dup = sorted({x for x in bs if bs.count(x) > 1})
        if dup:
            errs.append(f"page{page}: duplicate bytes {[hex(x) for x in dup]}")
        if sorted(bs) != expected_bytes(len(pl), page):
            errs.append(f"page{page}: bytes are not dense/sequential from 0x00 (0x80 skipped on page0)")
    for page, pl in pages.items():
        free = (255 if page == 0 else 256) - len(pl)
        print(f"page{page}: {len(pl)} opcodes, {free} free")
    if errs:
        print("FAIL:")
        for e in errs:
            print("  - " + e)
        return 1
    print("OK: dense, unique, in-range, within length budget")
    return 0


def emit_md(ops):
    out = []
    for page in (0, 1):
        pl = by_page(ops)[page]
        out += [f"#### Page {page} — {PAGE_TITLE[page]}, {len(pl)} opcodes", ""]
        groups = []
        for o in pl:
            if o["group"] not in groups:
                groups.append(o["group"])
        for g in groups:
            gops = [o for o in pl if o["group"] == g]
            toks = ", ".join(f"`{o['byte']:02X} {o['mnem']}`" for o in gops)
            out += [f"**{g} — {len(gops)}.**", toks, ""]
    return "\n".join(out).rstrip() + "\n"


def write_md(ops):
    md = ISA_MD.read_text()
    if BEGIN not in md or END not in md:
        sys.exit("inventory markers not found in docs/isa.md")
    pre, rest = md.split(BEGIN, 1)
    _, post = rest.split(END, 1)
    ISA_MD.write_text(f"{pre}{BEGIN}\n\n{emit_md(ops)}\n{END}{post}")
    print("docs/isa.md inventory rewritten from isa/opcodes.toml")


def emit_json(ops):
    keys = ("mnem", "page", "byte", "trailing", "length", "priv")
    print(json.dumps([{k: o[k] for k in keys} for o in ops], indent=2))


# ── assembler opcode table (as1-blip.c consumes this) ──
#
# The assembler matches a parsed line against a *normalized key*: the mnemonic
# verb plus its operand form with the operand-value placeholders collapsed
# ($nnnn/$nn/$n -> $i, n8/n16 -> n, rel8/rel16 -> rel, mask8 -> mask). The only
# keys that then collide are the off8/off16 width pairs, which the assembler
# resolves by operand range. as1-blip.c's normalizer must produce these exact
# keys; keep the two in lockstep.
_TRAIL = {
    "": "T_NONE", "imm8": "T_IMM8", "imm16": "T_IMM16",
    "off8": "T_OFF8", "off16": "T_OFF16", "abs16": "T_ABS16",
    "rel8": "T_REL8", "rel16": "T_REL16", "mask8": "T_MASK8",
    "movsel": "T_MOVSEL",
}


def asmkey(mnem):
    parts = mnem.split(None, 1)
    if len(parts) == 1:
        return parts[0]
    s = parts[1]
    s = s.replace("$nnnn", "$i").replace("$nn", "$i").replace("$n", "$i")
    s = s.replace("n16", "n").replace("n8", "n")
    s = s.replace("rel16", "rel").replace("rel8", "rel")
    s = s.replace("mask8", "mask")
    return parts[0] + " " + s


def emit_asmtab(ops):
    out = [
        "/* Generated by tools/isa/gen_opcodes.py emit-asmtab from isa/opcodes.toml.",
        " * DO NOT EDIT. Regenerated by tools/fcc/build.sh. */",
        "#ifndef BLIP_OPTAB_H",
        "#define BLIP_OPTAB_H",
        "",
        "enum {",
        "\tT_NONE, T_IMM8, T_IMM16, T_OFF8, T_OFF16,",
        "\tT_ABS16, T_REL8, T_REL16, T_MASK8, T_MOVSEL",
        "};",
        "",
        "struct optab { const char *key; unsigned char page, byte, trail; };",
        "",
        "static const struct optab blip_optab[] = {",
    ]
    for o in ops:
        t = o["trailing"]
        trail = _TRAIL[t[0]] if t else "T_NONE"
        out.append(f'\t{{ "{asmkey(o["mnem"])}", {o["page"]}, {o["byte"]:#04x}, {trail} }},')
    out += [
        "};",
        "",
        "#define BLIP_OPTAB_N (sizeof(blip_optab) / sizeof(blip_optab[0]))",
        "",
        "#endif",
    ]
    print("\n".join(out))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("cmd", choices=["check", "emit-md", "write-md", "emit-json", "emit-asmtab"])
    cmd = ap.parse_args().cmd
    ops = load()
    if cmd == "check":
        sys.exit(check(ops))
    if cmd == "emit-md":
        print(emit_md(ops))
    if cmd == "write-md":
        write_md(ops)
    if cmd == "emit-json":
        emit_json(ops)
    if cmd == "emit-asmtab":
        emit_asmtab(ops)


if __name__ == "__main__":
    main()
